name: Run Job Search Script

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-job-search-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Pytho
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}
          GOOGLE_SE_ID: ${{ secrets.GOOGLE_SE_ID}}
        run: |
          python job_search.py
      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-csv
          path: output.csv