name: Run Job Search Script

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-job-search-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}
          GOOGLE_SE_ID: ${{ secrets.GOOGLE_SE_ID}}
        run: |
          python job_search.py
      
      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-csv
          path: results.csv

      - name: Generate markdown table from CSV
        run: |
          python generate_md_table.py
          
      - name: Upload MD Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: email_body.md
          path: email_body.md
     
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.GOOGLE_APP_PASSWORD }}
          subject: Python Script Run Completed
          body: file://email_body.md
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          attachments: results.csv
          
