name: Run Job Search Script

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-job-search-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}
          GOOGLE_SE_ID: ${{ secrets.GOOGLE_SE_ID}}
        run: |
          python job_search.py
      
      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-csv
          path: results.csv

      - name: Generate markdown table from CSV
        run: |
          python generate_md_table.py
          echo email_body.md
      
      - id: read_md
        name: Read generated markdown table
        run: |
            markdown_output=$(cat email_body.md)
            markdown_output="${markdown_output//'%'/'%25'}"
            markdown_output="${markdown_output//$'\n'/'%0A'}"
            markdown_output="${markdown_output//$'\r'/'%0D'}"
            echo "markdown=$markdown_output" >> "$GITHUB_OUTPUT"
     
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          convert_markdown: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.GOOGLE_APP_PASSWORD }}
          subject: Python Script Run Completed
          html_body: ${{ steps.read_md.outputs.markdown }}
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          attachments: results.csv
          
