name: Run Job Search Script

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-job-search-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Pytho
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        run: |
          python job_search.py